I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gui.rpy", line 64, in script
    define gui.text_font = walkway_font_path
  File "game/gui.rpy", line 64, in script
    define gui.text_font = walkway_font_path
  File "game/gui.rpy", line 64, in <module>
    define gui.text_font = walkway_font_path
NameError: name 'walkway_font_path' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/gui.rpy", line 64, in script
    define gui.text_font = walkway_font_path
  File "game/gui.rpy", line 64, in script
    define gui.text_font = walkway_font_path
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/ast.py", line 2164, in execute
    self.set()
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/ast.py", line 2175, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/gui.rpy", line 64, in <module>
    define gui.text_font = walkway_font_path
NameError: name 'walkway_font_path' is not defined

Linux-5.4.0-64-generic-i686-with-debian-buster-sid
Ren'Py 7.4.1.1270
The Untold Path 1.0
Sat Jan 30 14:57:33 2021
